/**
 * Pricing mirror spec — asserts the storefront's DISPLAYED decoration
 * pricing (calculatePricing) matches what the backend actually CHARGES
 * (computeDecorationTotals via computeScpLineDescriptor), using the shared
 * golden vectors generated by the backend characterization harness:
 *
 *   backend/src/lib/__tests__/fixtures/pricing-shapes.json  (inputs)
 *   backend/src/lib/__tests__/fixtures/pricing-golden.json  (charged values)
 *
 * Order #44 (2026-08) shipped because these two drifted: the panel showed an
 * embroidered side priced as a DTF print while the backend (correctly)
 * charged embroidery — and then a second bug dropped the charge entirely.
 * The customizer's display math must live client-side for live UX, so drift
 * is prevented by this spec instead of by unification: if either side's
 * numbers move, this fails CI.
 *
 * Comparison is per decoration COMPONENT (print / embroidery / screen per
 * garment), not the discounted total — garment sourcing and quantity
 * discounts legitimately differ between display and charge paths.
 *
 * If this fails after a deliberate rate-card change: update BOTH sides
 * (backend lib + storefront mirror), regenerate the backend goldens
 * (UPDATE_PRICING_GOLDEN=1), and re-run.
 */
import fs from "fs"
import path from "path"

import { calculatePricing } from "./pricing"
import type {
  EmbroideryPricingSpec,
  GarmentSide,
  PrintPricingSpec,
  ScreenPricingSpec,
} from "./types"
import type { ScpPrintSizeId } from "./scp-dtf-print-pricing"

const FIXTURES = path.join(
  __dirname,
  "../../../../..",
  "backend/src/lib/__tests__/fixtures"
)

type ShapeCase = {
  name: string
  quantity: number
  design: {
    scpPrintSizeId: string | null
    prints: Array<{ side: string; sizeId?: string }> | null
    artifacts: Array<{ side: string; print_size_id?: string | null }> | null
    sideDecorationMethods: Record<string, string> | null
    sideEmbroideryConfigs: Record<
      string,
      { stitchCount?: number; includeDigitizingFee?: boolean }
    > | null
    sideScreenConfigs?: Record<string, { colours?: number; darkGarment?: boolean }> | null
    server: Record<string, unknown>
    printPlacement?: { side?: string }
  }
}

type GoldenCase = {
  descriptor: {
    printTotalMajor: number
    embroideryTotalMajor: number
    screenTotalMajor: number
  }
}

const shapes = JSON.parse(
  fs.readFileSync(path.join(FIXTURES, "pricing-shapes.json"), "utf8")
) as { cases: ShapeCase[] }
const golden = JSON.parse(
  fs.readFileSync(path.join(FIXTURES, "pricing-golden.json"), "utf8")
) as Record<string, GoldenCase>

const round2 = (n: number) => Math.round(n * 100) / 100

describe("storefront pricing mirrors the backend charge (shared golden vectors)", () => {
  for (const c of shapes.cases) {
    it(c.name, () => {
      const g = golden[c.name]
      expect(g).toBeDefined()

      const selectedSize = (c.design.scpPrintSizeId ??
        (c.design.server.print_size_id as string | null) ??
        "up_to_a6") as ScpPrintSizeId
      const methods = c.design.sideDecorationMethods ?? {}

      // Per-print entries: the customizer's Phase-B model. prints[] wins
      // over the legacy artifacts[] payload when both exist — the same
      // precedence decoratedLocationsFromLineMetadata applies server-side.
      // Legacy artifacts map 1:1 (one artifact = one print, size falls back
      // to the selected size — same fallback the backend applies).
      const printEntries: PrintPricingSpec[] = (c.design.prints?.length
        ? c.design.prints.map((p) => ({
            side: p.side,
            sizeId: p.sizeId ?? selectedSize,
          }))
        : (c.design.artifacts ?? []).map((a) => ({
            side: a.side,
            sizeId: a.print_size_id ?? selectedSize,
          }))
      ).map((p) => ({
        side: p.side as GarmentSide,
        sizeId: p.sizeId as ScpPrintSizeId,
      }))

      // Decorated sides for the legacy (no prints[]) path — printPlacement
      // metadata carries a single side.
      const decoratedSides: GarmentSide[] = printEntries.length
        ? Array.from(new Set(printEntries.map((p) => p.side)))
        : c.design.printPlacement?.side
        ? [c.design.printPlacement.side as GarmentSide]
        : []

      const embroidery: EmbroideryPricingSpec[] = decoratedSides
        .filter((side) => methods[side] === "embroidery")
        .map((side) => ({
          side,
          stitchCount: c.design.sideEmbroideryConfigs?.[side]?.stitchCount ?? 0,
          includeDigitizingFee:
            c.design.sideEmbroideryConfigs?.[side]?.includeDigitizingFee !== false,
        }))

      const screen: ScreenPricingSpec[] = decoratedSides
        .filter((side) => methods[side] === "screen")
        .map((side) => ({
          side,
          colours: c.design.sideScreenConfigs?.[side]?.colours ?? 1,
          darkGarment: c.design.sideScreenConfigs?.[side]?.darkGarment === true,
        }))

      const breakdown = calculatePricing({
        basePriceCents: Number(c.design.server.garment_unit_major ?? 0),
        decoratedSidesCount: decoratedSides.length,
        decoratedSides,
        totalQuantity: c.quantity,
        scpPrint: { printSizeId: selectedSize },
        prints: printEntries.length ? printEntries : undefined,
        embroidery,
        screen,
        // The backend goldens were generated without a product heavy-garment
        // flag (the harness runs DB-free), so mirror that here. The stored-
        // flag path is exercised by the backend recompute vectors.
        screenHeavyGarment: false,
      })

      // Component-by-component parity with what the backend charges.
      expect(round2(breakdown.sideSurchargePerUnitCents)).toBe(
        g.descriptor.printTotalMajor
      )
      expect(round2(breakdown.embroideryPerUnitCents ?? 0)).toBe(
        g.descriptor.embroideryTotalMajor
      )
      expect(round2(breakdown.screenPerUnitCents ?? 0)).toBe(
        g.descriptor.screenTotalMajor
      )
    })
  }
})
