/**
 * Quote job pricer — sell price from the LIVE rate cards, cost from the
 * cost-model workbook, margin per component. Pure (no container) so the
 * admin "Price a job" panel, the route and the tests all share one brain.
 *
 * SELL comes from the same modules checkout uses (dtf / supacolour / screen /
 * embroidery cards + the garment ladder or tier multiplier) — a quote can't
 * drift from the website price. COST mirrors the sheets of
 * `Drive/SC Print/SC-Prints-Cost-Model.xlsx` (regenerated by
 * `build_cost_model.py`); every constant below names its sheet + cell so the
 * two stay reconcilable. Margin = sell ÷ 1.1 − cost, exactly as the workbook's
 * red/black margin blocks compute it (sell is inc GST, cost is ex GST).
 *
 * Promo / trade and BYO cards (customer-supplied garments) live ONLY in the
 * workbook today ("Promo Pricing" / "BYO Pricing" sheets) — mirrored here.
 */
import {
  DIGITIZING_FEE_MAJOR,
  MAX_AUTO_PRICED_STITCHES,
  calculateEmbroideryUnitPriceMajor,
  resolveEmbroideryQuantityTier,
} from "./embroidery-pricing"
import {
  SCP_PRINT_SIZE_OPTIONS,
  resolveScpTierIndexForQuantity,
  scpPrintUnitMajorForTier,
  type ScpPrintSizeId,
} from "./scp-dtf-print-pricing"
import {
  SCREEN_HEAVY_GARMENT_SURCHARGE_MAJOR,
  SCREEN_MAX_QUANTITY,
  SCREEN_MIN_QUANTITY,
  SCREEN_REPEAT_SETUP_PER_SCREEN_MAJOR,
  SCREEN_SETUP_PER_SCREEN_MAJOR,
  screenUnitMajor,
} from "./scp-screen-print-pricing"
import {
  SUPACOLOUR_QUOTE_ONLY_SIZES,
  SUPACOLOUR_REPEAT_SETUP_MAJOR,
  SUPACOLOUR_SETUP_MAJOR,
  supacolourUnitMajorForTier,
} from "./scp-supacolour-pricing"

const GST = 0.1
const round2 = (n: number) => Math.round(n * 100) / 100
const exGst = (incMajor: number) => incMajor / (1 + GST)

// ---------------------------------------------------------------------------
// Cost basis (ex GST) — workbook "Inputs" dials
// ---------------------------------------------------------------------------
/** Inputs!B — loaded labour rate $/hr (owners' pay targets ÷ hands-on hours). */
export const LABOUR_RATE_HR = 95
/** Inputs — DSP roll $/lineal metre ex, 760mm roll (INV156518 31/07/26). */
const DTF_LM_RATE_EX = 38
/** Inputs — gaps / misprints / part-filled rows. */
const DTF_WASTAGE = 0.15
/** Inputs — press labour minutes per print (timed 2026-08-15). */
const PRESS_MINUTES = 2
const PRESS_LABOUR_EX = round2((PRESS_MINUTES / 60) * LABOUR_RATE_HR)

/** "DTF Pricing" rows 5-8: height mm + prints across the 760mm roll. */
const DTF_GEOMETRY: Record<ScpPrintSizeId, { heightMm: number; across: number }> = {
  up_to_a6: { heightMm: 148, across: 6 },
  up_to_a4: { heightMm: 297, across: 3 },
  up_to_a3: { heightMm: 420, across: 2 },
  oversize: { heightMm: 480, across: 2 },
}

/** DTF roll floor per print (ex GST) = transfer (row length × $/lm ÷ across × wastage) + press labour. */
export function dtfFloorExMajor(sizeId: ScpPrintSizeId): number {
  const g = DTF_GEOMETRY[sizeId]
  const rowLenM = (g.heightMm + 5) / 1000
  const transfer = (rowLenM * DTF_LM_RATE_EX) / g.across * (1 + DTF_WASTAGE)
  return round2(transfer + PRESS_LABOUR_EX)
}

/**
 * "Supacolour Costs" — DIRECT portal 2026-08-26, transfer only, ex GST.
 * Columns = Supacolour bands 20-49 / 50-99 / 100-249 (250+ bands unused —
 * our card tops out at 100+). Our tiers 0-1 (qty 1-19) price at 20-49.
 */
const SUPA_BAND_FOR_TIER = [0, 0, 0, 1, 2] as const
const SUPA_WEARABLE_EX: Partial<Record<ScpPrintSizeId, readonly [number, number, number]>> = {
  up_to_a6: [3.53, 3.01, 2.44], // WE-LC 100×100
  up_to_a4: [6.48, 5.68, 4.05], // WE-A4
  up_to_a3: [10.65, 9.39, 6.71], // WE-A3
}
const SUPA_BLOCKER_EX: Partial<Record<ScpPrintSizeId, readonly [number, number, number]>> = {
  up_to_a6: [4.05, 3.4, 2.9], // BL-LC
  up_to_a4: [7.18, 6.37, 4.76], // BL-A4
  up_to_a3: [11.81, 10.42, 7.76], // BL-A3
}
/** Supacolour setup COST, direct (new / reset). Retail $69 / $35 is in scp-supacolour-pricing. */
const SUPA_SETUP_COST_EX = { new: 40, repeat: 20 }

/**
 * "DTF Pricing" CHANNEL FLOOR: the cheapest supply channel per cell — DTF
 * roll, or (from qty 20) Supacolour wearable transfer + our press labour.
 */
export function fullColourFloorExMajor(sizeId: ScpPrintSizeId, tierIndex: number): number {
  const dtf = dtfFloorExMajor(sizeId)
  const supa = SUPA_WEARABLE_EX[sizeId]
  if (tierIndex < 2 || !supa) return dtf
  return round2(Math.min(dtf, supa[SUPA_BAND_FOR_TIER[tierIndex]] + PRESS_LABOUR_EX))
}

/** Supacolour BLOCKER applied cost (poly/blend garments) — transfer + press. */
export function supacolourBlockerCostExMajor(sizeId: ScpPrintSizeId, tierIndex: number): number | null {
  const row = SUPA_BLOCKER_EX[sizeId]
  if (!row) return null
  return round2(row[SUPA_BAND_FOR_TIER[Math.min(4, Math.max(0, tierIndex))]] + PRESS_LABOUR_EX)
}

/** "Screen Printing" — DSP price list 1 Mar 2024, ex GST per print, 1..6 colours. */
const SCREEN_DSP_COST_EX: ReadonlyArray<readonly [number, number, number, number, number, number]> = [
  [5.1, 6.29, 7.5, 8.7, 9.9, 11.2], // 25-49
  [3.05, 3.4, 3.95, 4.5, 5.1, 5.7], // 50-99
  [2.4, 2.85, 3.15, 3.4, 3.7, 4.15], // 100-199
  [1.95, 2.25, 2.45, 2.6, 2.75, 2.85], // 200-499
  [1.25, 1.4, 1.55, 1.7, 1.8, 1.9], // 500-999
]
const SCREEN_HANDLING_EX = 0.3
const SCREEN_HEAVY_COST_EX = 0.6
const SCREEN_SETUP_COST_EX = { new: 70, repeat: 25 }

/** "Embroidery" cost inputs. */
const EMB_STITCHES_PER_MIN = 600
const EMB_HOOP_MINUTES = 3
const EMB_HEADS_PER_OPERATOR = 3
const EMB_CONSUMABLES_EX = 0.25
/** GAA 2022 list, ex GST, by GAA band — only the columns our bands map onto (101-200 / 201-400 / 401+). */
const GAA_COST_EX: ReadonlyArray<readonly [number, number, number]> = [
  [2.3, 2.1, 2.0], // 3000
  [2.5, 2.3, 2.2],
  [2.7, 2.5, 2.3],
  [2.9, 2.7, 2.5],
  [3.1, 2.9, 2.7],
  [3.3, 3.1, 2.9],
  [3.4, 3.3, 3.1],
  [3.6, 3.5, 3.3],
  [3.8, 3.7, 3.5],
  [4.0, 3.9, 3.7], // 12000
]

/**
 * Embroidery cost per placement (ex GST): in-house up to 100 units (operator
 * time at the loaded rate + thread), GAA outsource above (the dearer
 * overlapping GAA band, as the workbook does). Under 3,000 stitches costs as 3,000.
 */
export function embroideryCostExMajor(stitchCount: number, quantity: number): number {
  const band = Math.min(12, Math.max(3, Math.ceil(stitchCount / 1000)))
  const { tierIndex } = resolveEmbroideryQuantityTier(quantity)
  if (tierIndex >= 3) return GAA_COST_EX[band - 3][tierIndex - 3]
  const runMin = (band * 1000) / EMB_STITCHES_PER_MIN
  const operatorMin = Math.max(EMB_HOOP_MINUTES, runMin / EMB_HEADS_PER_OPERATOR)
  return round2((operatorMin / 60) * LABOUR_RATE_HR + EMB_CONSUMABLES_EX)
}

/**
 * UV DTF — "UV DTF" sheet rows 5-14, all ex GST per lineal metre of 580mm
 * film. The machine overhead ÷ the VOLUME DIAL (Inputs, 40 lm/month) is the
 * whole floor story; everything else is cheap consumables + labour.
 */
const UV = {
  sqmPerLm: 0.58,
  inkPerLitre: 105,
  mlPerSqm: 8 + 14 + 10,
  maintenance: 0.15,
  filmPer100m: 480,
  wastage: 0.15,
  machine: 23000,
  machineYears: 5,
  heads: 4200,
  headYears: 3,
  serviceYear: 600,
  lmPerMonth: 40,
  kw: 0.65,
  tariff: 0.35,
  lmPerHour: 6,
  setupMinutes: 10,
  runMinutesPerLm: 6,
}
export function uvdtfFloorExPerLm(): number {
  const ink = UV.sqmPerLm * (UV.mlPerSqm / 1000) * UV.inkPerLitre * (1 + UV.maintenance)
  const film = UV.filmPer100m / 100
  const consumables = (ink + film) * (1 + UV.wastage)
  const machine =
    (UV.machine / UV.machineYears / 12 + UV.heads / UV.headYears / 12 + UV.serviceYear / 12) /
    UV.lmPerMonth
  const power = (UV.kw * UV.tariff) / UV.lmPerHour
  const labour = (UV.runMinutesPerLm / 60) * LABOUR_RATE_HR
  return round2(consumables + machine + power + labour)
}
const UV_SETUP_COST_EX = round2((UV.setupMinutes / 60) * LABOUR_RATE_HR)

// ---------------------------------------------------------------------------
// Sell cards that exist only in the workbook / storefront (mirrored here)
// ---------------------------------------------------------------------------
/**
 * UV DTF gang-sheet card, inc GST per lineal metre by total length. Mirror of
 * storefront `decoration/lib/methods/uvdtf-sheet.ts` (Card 2, 2026-09-03).
 */
export const UVDTF_RATE_BANDS = [
  { minMetres: 25, perMetre: 45 },
  { minMetres: 10, perMetre: 48 },
  { minMetres: 5, perMetre: 52 },
  { minMetres: 2, perMetre: 58 },
  { minMetres: 1, perMetre: 65 },
] as const
export const UVDTF_SETUP_INC = 25

/** "BYO Pricing" — handling fee per PRINT POSITION on customer-supplied garments, inc GST (Sean 2026-08-18). */
export const BYO_HANDLING_PER_POSITION_INC = 3

/** "Promo Pricing" — trade DTF card, EX GST per print position, their garments. */
const PROMO_DTF_EX: Record<ScpPrintSizeId, readonly [number, number, number, number, number]> = {
  up_to_a6: [6, 5.5, 5, 4.75, 4.5],
  up_to_a4: [9.25, 8.75, 8.25, 8, 7.75],
  up_to_a3: [14, 13.5, 13, 12.75, 12.5],
  oversize: [15.5, 15, 14.5, 14.25, 14],
}
/** "Promo Pricing" — press-only fee (they supply the transfers), EX GST per position. */
const PROMO_PRESS_ONLY_EX = [4.75, 4.25, 3.75, 3.5, 3.25] as const
/** "Promo Pricing" — trade embroidery card, EX GST per placement, 3k..12k rows × our 6 bands. */
const PROMO_EMB_EX: ReadonlyArray<readonly [number, number, number, number, number, number]> = [
  [7.5, 7, 6.25, 4.5, 3.5, 2.75],
  [7.5, 7, 6.25, 4.5, 3.75, 3],
  [7.5, 7, 6.25, 4.75, 4, 3.25],
  [8, 7.5, 6.75, 5, 4.25, 3.25],
  [8.75, 8.25, 7.5, 5.25, 4.5, 3.5],
  [9.75, 9.25, 8.5, 6, 5.25, 4.5],
  [10.5, 10, 9.25, 6.75, 6, 5.25],
  [11.5, 11, 10.25, 7.75, 6.75, 6],
  [12.25, 11.75, 11, 8.5, 7.75, 6.75],
  [13.25, 12.75, 12, 9.25, 8.5, 7.75],
]

// ---------------------------------------------------------------------------
// Spec → components
// ---------------------------------------------------------------------------
export const PRINT_CHANNELS = ["dtf", "supacolour", "byo", "promo", "press_only"] as const
export type PrintChannel = (typeof PRINT_CHANNELS)[number]

export type QuoteJobSpec = {
  /** Garments (job quantity — drives every tier). */
  quantity: number
  /** Full-colour print positions. */
  prints?: Array<{ sizeId: ScpPrintSizeId }>
  /**
   * Which full-colour card: dtf (our cotton garment), supacolour (our poly
   * garment — auto when the product is flagged), byo (their garment, retail
   * card + handling), promo (trade card, ex GST), press_only (they supply transfers).
   */
  printChannel?: PrintChannel
  supacolourRepeatSetup?: boolean
  screen?: {
    positions: Array<{ colours: number; darkGarment?: boolean }>
    heavyGarment?: boolean
    repeatSetup?: boolean
  }
  embroidery?: Array<{ stitchCount: number; digitizing?: boolean }>
  /** Trade embroidery card (their garments, ex GST). */
  embroideryPromo?: boolean
  uvdtf?: { metres: number; reorder?: boolean }
}

/** Garment resolved by the route (ladder / tier sell, importer cost). */
export type ResolvedGarment = {
  title: string
  /** Inc-GST unit sell at this quantity (ladder tier or flat tier price). */
  unitSellMajor: number | null
  /** Supplier trade price ex GST (variant.metadata.cost_price_ex_gst_minor ÷ 100). */
  unitCostExMajor: number | null
  /** True when the cost was back-derived from the 100+ ladder rather than stamped by an importer. */
  costEstimated?: boolean
  supacolour: boolean
  screenHeavy: boolean
}

export type QuotePriceComponent = {
  key: string
  label: string
  /** per_garment components sum into the garment line; per_metre is its own line; setup is its own line. */
  kind: "per_garment" | "per_metre" | "setup"
  quantity: number
  unitSellMajor: number
  unitCostExMajor: number | null
  sellTotalMajor: number
  costTotalExMajor: number | null
  /** sellTotal ÷ 1.1 − costTotal. */
  marginExMajor: number | null
  /** Margin as a share of the ex-GST sell. */
  marginPct: number | null
  /** Which hidden service product carries this setup fee on the cart (null = custom line). */
  setupProduct?: "screen_setup" | "supacolour_setup" | "embroidery_setup" | null
  requiresQuote?: boolean
  notes?: string[]
}

export type QuoteJobPrice = {
  components: QuotePriceComponent[]
  warnings: string[]
  /** Per-garment unit sell (garment + per-garment decoration), inc GST. */
  perGarmentSellMajor: number
  /** Cost + margin cover only the components with a known cost; the rest are listed. */
  totals: {
    sellIncMajor: number
    costExMajor: number | null
    marginExMajor: number | null
    marginPct: number | null
    unknownCostKeys: string[]
  }
}

const component = (
  c: Omit<QuotePriceComponent, "sellTotalMajor" | "costTotalExMajor" | "marginExMajor" | "marginPct">
): QuotePriceComponent => {
  const sellTotalMajor = round2(c.unitSellMajor * c.quantity)
  const costTotalExMajor = c.unitCostExMajor == null ? null : round2(c.unitCostExMajor * c.quantity)
  const sellEx = exGst(sellTotalMajor)
  const marginExMajor = costTotalExMajor == null ? null : round2(sellEx - costTotalExMajor)
  const marginPct =
    marginExMajor == null || sellEx <= 0 ? null : Math.round((marginExMajor / sellEx) * 1000) / 10
  return { ...c, sellTotalMajor, costTotalExMajor, marginExMajor, marginPct }
}

const sizeLabel = (id: ScpPrintSizeId) =>
  SCP_PRINT_SIZE_OPTIONS.find((o) => o.id === id)?.label ?? id

export function priceQuoteJob(spec: QuoteJobSpec, garment: ResolvedGarment | null): QuoteJobPrice {
  const qty = Math.max(1, Math.floor(spec.quantity || 1))
  const tierIndex = resolveScpTierIndexForQuantity(qty)
  const components: QuotePriceComponent[] = []
  const warnings: string[] = []

  if (garment) {
    if (garment.unitSellMajor == null) warnings.push(`${garment.title}: no catalogue price — set the unit price by hand.`)
    components.push(
      component({
        key: "garment",
        label: garment.title,
        kind: "per_garment",
        quantity: qty,
        unitSellMajor: garment.unitSellMajor ?? 0,
        unitCostExMajor: garment.unitCostExMajor,
        notes:
          garment.unitCostExMajor == null
            ? ["No supplier cost on this variant — margin unknown."]
            : garment.costEstimated
              ? ["Cost estimated from the 100+ ladder (no supplier cost stamped on this variant)."]
              : undefined,
      })
    )
  }

  // --- full-colour prints ---
  const channel: PrintChannel =
    spec.printChannel ?? (garment?.supacolour ? "supacolour" : "dtf")
  const prints = spec.prints ?? []
  if (prints.length && (channel === "byo" || channel === "promo" || channel === "press_only") && garment) {
    warnings.push("BYO / trade print cards are for customer-supplied garments — remove the catalogue garment or switch the card.")
  }
  prints.forEach((p, i) => {
    const pos = `position ${i + 1}`
    if (channel === "supacolour") {
      if (SUPACOLOUR_QUOTE_ONLY_SIZES.has(p.sizeId)) {
        warnings.push(`Supacolour has no ${sizeLabel(p.sizeId)} transfer — price that position by hand.`)
        components.push(
          component({ key: `print-${i}`, label: `Supacolour ${sizeLabel(p.sizeId)} (${pos})`, kind: "per_garment", quantity: qty, unitSellMajor: 0, unitCostExMajor: null, requiresQuote: true })
        )
        return
      }
      components.push(
        component({
          key: `print-${i}`,
          label: `Supacolour transfer ${sizeLabel(p.sizeId)} (${pos})`,
          kind: "per_garment",
          quantity: qty,
          unitSellMajor: supacolourUnitMajorForTier(p.sizeId, tierIndex) ?? 0,
          unitCostExMajor: supacolourBlockerCostExMajor(p.sizeId, tierIndex),
        })
      )
      return
    }
    if (channel === "press_only") {
      components.push(
        component({ key: `print-${i}`, label: `Press only ${sizeLabel(p.sizeId)} (${pos}, trade ex GST + GST)`, kind: "per_garment", quantity: qty, unitSellMajor: round2(PROMO_PRESS_ONLY_EX[tierIndex] * (1 + GST)), unitCostExMajor: PRESS_LABOUR_EX })
      )
      return
    }
    const cost = fullColourFloorExMajor(p.sizeId, tierIndex)
    if (channel === "promo") {
      components.push(
        component({ key: `print-${i}`, label: `Trade DTF ${sizeLabel(p.sizeId)} (${pos}, ex GST card + GST)`, kind: "per_garment", quantity: qty, unitSellMajor: round2(PROMO_DTF_EX[p.sizeId][tierIndex] * (1 + GST)), unitCostExMajor: cost })
      )
      return
    }
    const retail = scpPrintUnitMajorForTier(p.sizeId, tierIndex)
    components.push(
      component({
        key: `print-${i}`,
        label: `${channel === "byo" ? "BYO " : ""}DTF print ${sizeLabel(p.sizeId)} (${pos})`,
        kind: "per_garment",
        quantity: qty,
        unitSellMajor: channel === "byo" ? round2(retail + BYO_HANDLING_PER_POSITION_INC) : retail,
        unitCostExMajor: cost,
      })
    )
  })
  if (channel === "supacolour" && prints.some((p) => !SUPACOLOUR_QUOTE_ONLY_SIZES.has(p.sizeId))) {
    const repeat = spec.supacolourRepeatSetup === true
    const designs = prints.filter((p) => !SUPACOLOUR_QUOTE_ONLY_SIZES.has(p.sizeId)).length
    components.push(
      component({
        key: "supacolour-setup",
        label: `Supacolour setup (${repeat ? "repeat" : "new"}, per design)`,
        kind: "setup",
        quantity: designs,
        unitSellMajor: repeat ? SUPACOLOUR_REPEAT_SETUP_MAJOR : SUPACOLOUR_SETUP_MAJOR,
        unitCostExMajor: repeat ? SUPA_SETUP_COST_EX.repeat : SUPA_SETUP_COST_EX.new,
        setupProduct: "supacolour_setup",
      })
    )
  }

  // --- screen print ---
  if (spec.screen?.positions.length) {
    if (qty < SCREEN_MIN_QUANTITY) warnings.push(`Screen printing minimum is ${SCREEN_MIN_QUANTITY} — ${qty} prices at the 25–49 band.`)
    if (qty > SCREEN_MAX_QUANTITY) warnings.push(`Over ${SCREEN_MAX_QUANTITY} screen prints — get a DSP quote; card tops out at the 500–999 band.`)
    const heavy = spec.screen.heavyGarment ?? garment?.screenHeavy ?? false
    let screens = 0
    spec.screen.positions.forEach((pos, i) => {
      const r = screenUnitMajor({ quantity: qty, colours: pos.colours, darkGarment: pos.darkGarment, heavyGarment: heavy })
      screens += r.effectiveColours
      const cost = round2(
        SCREEN_DSP_COST_EX[r.tierIndex][r.effectiveColours - 1] + SCREEN_HANDLING_EX + (heavy ? SCREEN_HEAVY_COST_EX : 0)
      )
      components.push(
        component({
          key: `screen-${i}`,
          label: `Screen print ${r.effectiveColours} colour${r.effectiveColours > 1 ? "s" : ""}${pos.darkGarment ? " incl. underbase" : ""}${heavy ? " + heavy garment" : ""} (position ${i + 1})`,
          kind: "per_garment",
          quantity: qty,
          unitSellMajor: r.unitMajor,
          unitCostExMajor: cost,
          notes: heavy ? [`Heavy-garment surcharge $${SCREEN_HEAVY_GARMENT_SURCHARGE_MAJOR} retail / $${SCREEN_HEAVY_COST_EX} cost.`] : undefined,
        })
      )
    })
    const repeat = spec.screen.repeatSetup === true
    components.push(
      component({
        key: "screen-setup",
        label: `Screen setup (${repeat ? "repeat" : "new"}, per screen)`,
        kind: "setup",
        quantity: screens,
        unitSellMajor: repeat ? SCREEN_REPEAT_SETUP_PER_SCREEN_MAJOR : SCREEN_SETUP_PER_SCREEN_MAJOR,
        unitCostExMajor: repeat ? SCREEN_SETUP_COST_EX.repeat : SCREEN_SETUP_COST_EX.new,
        setupProduct: "screen_setup",
      })
    )
  }

  // --- embroidery ---
  let digitizingFiles = 0
  ;(spec.embroidery ?? []).forEach((e, i) => {
    const stitches = Math.max(1, Math.floor(e.stitchCount || 0))
    if (stitches > MAX_AUTO_PRICED_STITCHES) {
      warnings.push(`Embroidery placement ${i + 1}: ${stitches.toLocaleString()} stitches is over the ${MAX_AUTO_PRICED_STITCHES.toLocaleString()} cap — price by hand.`)
      components.push(
        component({ key: `emb-${i}`, label: `Embroidery ${stitches.toLocaleString()} st (placement ${i + 1})`, kind: "per_garment", quantity: qty, unitSellMajor: 0, unitCostExMajor: embroideryCostExMajor(12000, qty), requiresQuote: true })
      )
      return
    }
    if (e.digitizing !== false) digitizingFiles += 1
    const cost = embroideryCostExMajor(stitches, qty)
    if (spec.embroideryPromo) {
      const band = Math.min(12, Math.max(3, Math.ceil(stitches / 1000)))
      const { tierIndex: t } = resolveEmbroideryQuantityTier(qty)
      components.push(
        component({ key: `emb-${i}`, label: `Trade embroidery ${stitches.toLocaleString()} st (placement ${i + 1}, ex GST card + GST)`, kind: "per_garment", quantity: qty, unitSellMajor: round2(PROMO_EMB_EX[band - 3][t] * (1 + GST)), unitCostExMajor: cost })
      )
      return
    }
    const r = calculateEmbroideryUnitPriceMajor({ stitchCount: stitches, quantity: qty, includeDigitizing: false })
    components.push(
      component({ key: `emb-${i}`, label: `Embroidery ${stitches.toLocaleString()} st (placement ${i + 1}, ${r.tierLabel} band)`, kind: "per_garment", quantity: qty, unitSellMajor: r.unitDecorationMajor, unitCostExMajor: cost, notes: qty > 100 ? ["Over 100 units — costed at GAA outsource rates (2022 list)."] : undefined })
    )
  })
  if (digitizingFiles > 0) {
    components.push(
      component({
        key: "digitizing",
        label: "Digitizing (per design, waived on reorders)",
        kind: "setup",
        quantity: digitizingFiles,
        unitSellMajor: DIGITIZING_FEE_MAJOR,
        unitCostExMajor: 0,
        setupProduct: "embroidery_setup",
        notes: ["Cost is owner time in-house (GAA charges $30–100 if outsourced)."],
      })
    )
  }

  // --- UV DTF gang sheets ---
  if (spec.uvdtf && spec.uvdtf.metres > 0) {
    const metres = Math.max(1, Math.floor(spec.uvdtf.metres))
    const rate = UVDTF_RATE_BANDS.find((b) => metres >= b.minMetres)?.perMetre ?? 65
    components.push(
      component({ key: "uvdtf", label: `UV DTF gang sheet 580mm (${metres} m)`, kind: "per_metre", quantity: metres, unitSellMajor: rate, unitCostExMajor: uvdtfFloorExPerLm(), notes: [`Floor assumes ${UV.lmPerMonth} lm/month through the Sublistar — machine overhead is most of it.`] })
    )
    if (!spec.uvdtf.reorder) {
      components.push(
        component({ key: "uvdtf-setup", label: "UV DTF setup / artwork", kind: "setup", quantity: 1, unitSellMajor: UVDTF_SETUP_INC, unitCostExMajor: UV_SETUP_COST_EX, setupProduct: null })
      )
    }
  }

  const perGarmentSellMajor = round2(
    components.filter((c) => c.kind === "per_garment").reduce((s, c) => s + c.unitSellMajor, 0)
  )
  const sellIncMajor = round2(components.reduce((s, c) => s + c.sellTotalMajor, 0))
  // Totals over the components whose cost is known — an unknown garment cost
  // shouldn't blank the decoration margin staff can still see.
  const costed = components.filter((c) => c.costTotalExMajor != null)
  const unknownCostKeys = components.filter((c) => c.costTotalExMajor == null).map((c) => c.key)
  const costedSellEx = exGst(costed.reduce((s, c) => s + c.sellTotalMajor, 0))
  const costExMajor = costed.length ? round2(costed.reduce((s, c) => s + (c.costTotalExMajor ?? 0), 0)) : null
  const marginExMajor = costExMajor == null ? null : round2(costedSellEx - costExMajor)
  const marginPct =
    marginExMajor == null || costedSellEx <= 0 ? null : Math.round((marginExMajor / costedSellEx) * 1000) / 10

  return {
    components,
    warnings,
    perGarmentSellMajor,
    totals: { sellIncMajor, costExMajor, marginExMajor, marginPct, unknownCostKeys },
  }
}
