import { z } from "zod"

// Generated by scripts/pantone/build-chart.mjs from the Pantone books — edit the
// script's list, not this JSON.
import rawChart from "../../../data/pantone-screen-chart.json"

const pantoneColorSchema = z.object({
  name: z.string(),
  hex: z.string().regex(/^#[0-9A-F]{6}$/),
  /** CIE Lab from the book (D50) — the value a RIP or ink-mixing app actually targets. */
  lab: z.tuple([z.number(), z.number(), z.number()]),
  notes: z.string().optional(),
})

const pantoneCategorySchema = z.object({
  category: z.string(),
  description: z.string(),
  colors: z.array(pantoneColorSchema),
})

/** Every colour the studio has pressed, in book order. Name + hex only — it is ~2,600 rows. */
const librarySchema = z.array(pantoneColorSchema.pick({ name: true, hex: true }))

export type PantoneColor = z.infer<typeof pantoneColorSchema>
export type PantoneCategory = z.infer<typeof pantoneCategorySchema>
export type PantoneSwatch = z.infer<typeof librarySchema>[number]

export const pantoneChart = z
  .object({ pantone_chart: z.array(pantoneCategorySchema), library: librarySchema })
  .parse(rawChart)
